import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const percent = value => value == null ? 'Unavailable' : `${Math.round(value * 100)}%`;
const tone = m => m.state === 'FAULT' || m.health_score < 40 ? 'critical' : m.health_score < 75 ? 'warning' : 'healthy';
async function get(path, signal) {
  const response = await fetch(path, {signal});
  if (!response.ok) throw new Error(`Request failed (${response.status})`);
  return response.json();
}

function Trend({events, field, label, unit}) {
  if (!events.length) return <p>No telemetry available.</p>;
  const values = events.map(e => e[field]);
  const min = Math.min(...values), max = Math.max(...values);
  const points = values.map((value, i) => `${i * 600 / Math.max(1, values.length - 1)},${85 - (value-min)/Math.max(.001,max-min)*65}`).join(' ');
  return <div className="trend"><div className="row"><span>{label}</span><strong>{values.at(-1).toFixed(2)} <small>{unit}</small></strong></div>
    <svg viewBox="0 0 600 100" role="img" aria-label={`${label}: ${min.toFixed(2)} to ${max.toFixed(2)} ${unit}, oldest to newest`}><path d="M0 85H600" stroke="#e0e6eb"/><polyline points={points} fill="none" stroke="#188b87" strokeWidth="2.5"/></svg>
    <div className="row muted"><small>Last {events.length} readings · oldest → newest</small><small>{min.toFixed(2)}–{max.toFixed(2)} {unit}</small></div></div>;
}

function App() {
  const [machines, setMachines] = useState([]), [metrics, setMetrics] = useState({});
  const [selected, setSelected] = useState(null), [events, setEvents] = useState([]), [alerts, setAlerts] = useState([]);
  const [report, setReport] = useState(null), [page, setPage] = useState('equipment');
  const [error, setError] = useState(''), [detailError, setDetailError] = useState(''), [filter, setFilter] = useState('all');
  useEffect(() => {
    const controller = new AbortController(); let timer;
    async function refresh() {
      try {
        const [m, stats, process] = await Promise.all(['/machines', '/metrics', '/process/report'].map(path => get(path, controller.signal)));
        setMachines(m); setMetrics(stats); setReport(process); setError('');
        setSelected(current => current || m[0]?.machine_id || null);
      } catch (err) { if (err.name !== 'AbortError') setError('Connection interrupted. Showing the last received data.'); }
      if (!controller.signal.aborted) timer = setTimeout(refresh, 2000);
    }
    refresh(); return () => { controller.abort(); clearTimeout(timer); };
  }, []);
  useEffect(() => {
    if (!selected) return;
    const controller = new AbortController(); let timer;
    setEvents([]); setAlerts([]);
    async function refresh() {
      try {
        const [history, activity] = await Promise.all(['telemetry', 'alerts'].map(part => get(`/machines/${selected}/${part}`, controller.signal)));
        setEvents(history); setAlerts(activity); setDetailError('');
      } catch (err) { if (err.name !== 'AbortError') setDetailError('Could not load equipment history.'); }
      if (!controller.signal.aborted) timer = setTimeout(refresh, 2000);
    }
    refresh(); return () => { controller.abort(); clearTimeout(timer); };
  }, [selected]);
  const current = machines.find(m => m.machine_id === selected);
  const online = machines.filter(m => Date.now() - m.timestamp_ms < 15000).length;
  return <><aside><a className="brand" href="/">◈ <span>FabTwin<small>MANUFACTURING INTELLIGENCE</small></span></a><div className="nav-label">WORKSPACE</div><nav>
    <button className={page === 'equipment' ? 'active' : ''} onClick={() => setPage('equipment')}>▦ &nbsp; Equipment overview</button>
    <button className={page === 'process' ? 'active' : ''} onClick={() => setPage('process')}>◉ &nbsp; Process & yield</button></nav>
    <div className="sidebar-note"><span className="dot"/> SIMULATION ENVIRONMENT<p>Equipment telemetry is generated by the C++ simulator. Process analysis uses UCI SECOM.</p></div></aside>
    <main><header><div className="eyebrow">FAB OPERATIONS / {page === 'equipment' ? 'EQUIPMENT' : 'PROCESS'}</div><div className="row"><h1>{page === 'equipment' ? 'Equipment health' : 'Process & yield'}</h1><span className="live"><span className="dot"/> {error ? 'Disconnected' : 'Refreshes every 2s'}</span></div><p className="subtitle">{page === 'equipment' ? 'A connected view of your equipment, signals, and maintenance priorities.' : 'Independent analysis of anonymized semiconductor process measurements.'}</p></header>
    {error && <div className="error" role="alert">{error}</div>}
    {page === 'equipment' ? <><section className="stats">{[['Machines online', online, `${machines.length} registered`], ['Healthy', machines.filter(m=>tone(m)==='healthy').length, 'Health score ≥ 75'], ['Warning', machines.filter(m=>tone(m)==='warning').length, 'Inspection recommended'], ['Critical', machines.filter(m=>tone(m)==='critical').length, 'Immediate attention']].map(([title,value,description])=><article key={title}><span>{title}</span><strong>{value.toString().padStart(2,'0')}</strong><small>{description}</small></article>)}</section>
    <div className="workspace"><section className="panel fleet"><div className="panel-heading"><h2>Equipment fleet <span>{machines.length}</span></h2><label className="sr-only" htmlFor="filter">Filter equipment</label><select id="filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All equipment</option><option value="healthy">Healthy</option><option value="warning">Warning</option><option value="critical">Critical</option></select></div>
    {!machines.length && <div className="empty">No equipment connected.<p>Start the edge simulator and streaming consumer to see live twins.</p></div>}
    <div className="machine-list">{machines.filter(m=>filter==='all'||tone(m)===filter).map(m=><button key={m.machine_id} className={`machine ${selected===m.machine_id?'selected':''}`} onClick={()=>setSelected(m.machine_id)}><div className="row"><strong>{m.machine_id.replace('_','-')}</strong><span className={`badge ${tone(m)}`}>{m.state}</span></div><div className="row muted"><small>{m.machine_id.split('_')[0].toLowerCase()} equipment</small><small>{Date.now()-m.timestamp_ms > 15000 ? 'Stale telemetry' : 'Receiving data'}</small></div><div className="healthbar"><i style={{width:`${m.health_score}%`}} className={tone(m)}/></div><div className="row"><small>Health <b>{m.health_score}/100</b></small><small>Failure risk <b>{percent(m.failure_probability)}</b></small></div></button>)}</div></section>
    <section className="panel detail">{current ? <><div className="panel-heading"><div><div className="eyebrow">EQUIPMENT DETAIL</div><h2>{current.machine_id.replace('_','-')}</h2></div><span className={`badge ${tone(current)}`}>{current.state}</span></div><div className="detail-stats"><div><small>Health score</small><strong>{current.health_score}<span>/100</span></strong></div><div><small>Failure risk</small><strong>{percent(current.failure_probability)}</strong></div><div><small>Anomaly percentile</small><strong>{percent(current.anomaly_score)}</strong></div></div>
      <p className="model-note">{current.prediction_source === 'unavailable' ? 'Model prediction unavailable for this equipment state or model not trained.' : `Simulator-trained model · next ${current.prediction_horizon_cycles} operating cycles`}</p>
      {current.primary_deviations.length > 0 && <div className="deviations"><strong>Signal deviations</strong><p>{current.primary_deviations.join(' · ')}</p><small>Threshold observations, not causal model explanations.</small></div>}
      {detailError && <p role="alert">{detailError}</p>}<Trend events={events} field="vibration" label="Vibration" unit="sim. units"/><Trend events={events} field="temperature" label="Temperature" unit="°C"/>
      <h3>Maintenance activity</h3>{!alerts.length ? <p className="muted">No maintenance alerts for this equipment.</p> : <div className="activity">{alerts.slice(0,8).map(a=><div key={a.id}><span className={`activity-dot ${a.resolved_ms?'resolved':''}`}/><div><strong>{a.kind.replaceAll('_',' ')}</strong><p>{a.message}</p><small>{new Date(a.created_ms).toLocaleString()} · {a.resolved_ms ? 'Resolved' : 'Open'}</small></div></div>)}</div>}
    </> : <div className="empty">Select equipment to inspect its signals.</div>}</section></div><footer><span>{(metrics.events_processed || 0).toLocaleString()} events persisted</span><span>p95 ingestion latency: {metrics.p95_ingestion_latency_ms == null ? '—' : `${metrics.p95_ingestion_latency_ms.toLocaleString()} ms`} · includes replay delay</span></footer></> : <section className="panel process"><div className="eyebrow">REAL SEMICONDUCTOR PROCESS DATA</div><h2>UCI SECOM · Yield risk analysis</h2>{report?.status === 'trained' ? <><p>{report.rows.toLocaleString()} observations · {report.observed_process_columns} anonymous process columns · {report.split}</p><div className="stats">{['precision','recall','f1','pr_auc_average_precision'].map(key=><article key={key}><span>{key.replaceAll('_',' ')}</span><strong>{report.metrics[key].toFixed(3)}</strong></article>)}</div><h3>Signals associated with yield risk</h3><p>Held-out permutation importance: decrease in average precision when a column is shuffled.</p><table><thead><tr><th>Process signal</th><th>PR-AUC decrease</th></tr></thead><tbody>{report.top_process_signals.map(item=><tr key={item.feature}><td>{item.feature}</td><td>{item.pr_auc_decrease.toFixed(4)}</td></tr>)}</tbody></table><p className="model-note">{report.limitation}</p></> : <div className="empty">SECOM analysis has not been trained yet.<p>Download the official dataset and run the independent process training pipeline.</p></div>}</section>}</main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
